### ISSUE TITLE
Make it possible to pass request specific context (e.g. using cookies) to GraphQL server

### ISSUE THREAD

**Issue by denvned** [denvned/isomorphic-relay#22]
This should be possible when Relay merges https://github.com/facebook/relay/pull/704

**Comment by 03eltond** [comment]
Hello there!  Curious how this will work... do you intend to allow passing a contextual RelayNetworkLayer to prepareData()?

**Comment by denvned** [comment]
@03eltond, the PR is merged, so with the next version of Relay it should be possible. Also before that I plan to release experimental version _isomorphic-relay_ which will use not yet NPM released version of Relay from GitHub.

**Comment by fenos** [comment]
That's great to hear, @denvned Thank you very much for the great job, keeping Relay capable of being isomorphic with its previous limitations. I Hope you will improve isomorphic-relay so that in the future it could be used as an add-on of  the relay ismorphic stack, offering some unique functionality. I think that you been interested about isormophism  with relay, it would be great if in a future you could share your experience building a web-app with this architecture. I hope i will do the same one day :).

**Comment by denvned** [comment]
@fenos 

> it would be great if in a future you could share your experience building a web-app with this architecture.

Actually, I already did it today: https://github.com/denvned/isomorphic-relay-boilerplate :smile:
And I plan to improve it with time.

**Comment by fenos** [comment]
:+1:  Thanks a lot!

**Comment by tuananhtd** [comment]
Hi @denvned is there any progress on the **experimental version isomorphic-relay**? Can't wait to see that. I would be more than willing to help if I can.

**Comment by denvned** [comment]
@tuananhtd, Yes, I'm working on it now. I hope to finish it in the next couple days.

**Comment by denvned** [comment]
Looks like it is finally solved. Now, in v0.6 of _isomorphic-relay_, it is possible to pass an instance of Relay network layer as the second argument to `IsomorphicRelay.prepareData`.
